name: Neovim checkhealth
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main

jobs:
  checkhealth:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        neovim: [v0.10.0, stable, nightly]

    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim: ${{ matrix.neovim }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim }}

      - name: Run :checkhealth
        uses: ColinKennedy/nvim-checkhealth-gh-action@v1.1.1
        with:
          executable: 'nvim -u "spec/minimal_init.lua"'
          checks: "plugin_template vim.*"
