name: llscheck

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main

jobs:
  llscheck:
    runs-on: ubuntu-latest
    name: llscheck

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      # NOTE: We need Neovim installed in order to expose the $VIMRUNTIME
      # environment variable
      with:
        neovim: true
        version: stable

    - name: Install A Lua Interpreter
      uses: leafo/gh-actions-lua@v11
      with:
        # Neovim is compiled with LuaJIT so we might as well match. But it
        # doesn't look like we can match it exactly.
        #
        # Reference:
        #    https://github.com/leafo/gh-actions-lua/issues/49#issuecomment-2295071198
        #
        luaVersion: "luajit-openresty"

    - name: Install lua-language-server
      uses: jdx/mise-action@v2
      with:
        tool_versions: |
          lua-language-server latest

    - name: Install luarocks
      # TODO: Replace with https://github.com/luarocks/gh-actions-luarocks after v6+
      uses: ColinKennedy/gh-actions-luarocks@v1.0.0

    - name: Print Versions
      run: |
        luarocks --version
        lua-language-server --version

    - name: Install llscheck
      run: |
        luarocks --version
        luarocks install llscheck --verbose

    - name: Test
      run: |
        # We use SSH in the `Makefile` but GitHub actions don't allow that. So
        # we force git to clone using HTTP instead.
        #
        export GIT_CONFIG=~/.gitconfig
        git config url."https://github.com/".insteadOf git@github.com:

        # Now do the llscheck (and any git clones, as needed)
        make llscheck CONFIGURATION=.github/workflows/.luarc.json
